/* Host adapter around canonical VisionWeaver Director Studio. Domain views and production records stay canonical. */
const HOSTED_UI_RELEASE='0.4.02';
const HOST_NAV=[['Home',[['command','Home','⌂'],['visionbuilder','Vision Builder','VB'],['strategy','Strategic Planner','SP'],['initiatives','Initiatives','IN'],['portfolio','Programs & Projects','PP'],['copilot','AI Co-Pilot','AI'],['cmi','CMI','CM'],['guild','Directors Guild','DG'],['teamsops','Teams & C-Suite','TM']]],['Create & Produce',[['source','Book Creation','BK'],['avatarops','Avatar Engineering','AV'],['worldops','Worlds & Locations','WL'],['design','Design Studio','DS'],['designops','Design & Commercial','DC'],['commercial','Commercial Creativity','AD'],['sceneproduction','Scene & Production','SC'],['postproduction','Post Production','PP'],['distribution','Distribution & Growth','DG']]],['Manage & Govern',[['qualityops','Quality & Audit','QA'],['financeops','Finance & Accounting','FA'],['itops','IT & Security','IT'],['resources','Resources','RE'],['assets','Assets & Knowledge','AK'],['reports','Reports & Insights','RI'],['settings','Settings','⚙']]],['Production tools',[['overview','Run of show','RS'],['locks','Locks & maps','LM'],['cast','Cast Board','CB'],['shots','Shot bible','SH'],['pictures','Pictures','IM'],['motion','Motion','MO'],['booth','Narration booth','VO'],['sound','Sound & music','AU'],['edit','Edit timeline','ED'],['deliver','Delivery','DL'],['publish','Publish & social','PU'],['setup','Connections','CO'],['rights','Rights & provenance','RP'],['database','Database','DB'],['activity','Activity log','LG'],['ledger','Credit ledger','CL'],['uploads','Uploads','UP'],['memoryops','History & Memory','HM'],['uplink','Claude uplink','CU']]]];
NAV.splice(0,NAV.length,...HOST_NAV);
V.sceneproduction=()=>vwHead('sceneproduction','Scene · production · continuity','Continue the existing shot records, cast locks, and production evidence.')+V.shots();
V.postproduction=()=>vwHead('postproduction','Edit · finish · delivery','Use the canonical editing tools, narration, sound, and delivery records.')+V.edit();
V.distribution=()=>vwHead('distribution','Distribution · channel preparation','Prepare releases from approved production records.')+V.publish();
if(!V.resources)V.resources=()=>'<div class="vhead"><h1>Resources</h1><p>Production references, tools, and canonical source records.</p></div><section class="panel"><div class="row"><button class="btn" data-view="locks">Locks & maps</button><button class="btn" data-view="setup">Connections</button><button class="btn" data-view="source">Books & script</button><button class="btn" data-view="rights">Rights & provenance</button></div></section>';
if(!V.assets)V.assets=()=>'<div class="vhead"><h1>Assets & Knowledge</h1><p>Preserved keyframes, reference locks, files, and rights records.</p></div>'+V.pictures();
const HOST_ORIGINAL_DESIGN=V.design;
V.design=()=>vwHead('design','Create · customize · brand · produce','The shared Design Studio editor remains connected to the production system.')+HOST_ORIGINAL_DESIGN()+ '<p class="note"><a href="/design-studio/" target="_blank" rel="noopener">Open standalone Design Studio ↗</a></p>';
const HOST_ORIGINAL_RAIL=renderRail;
renderRail=function(){HOST_ORIGINAL_RAIL();const r=document.querySelector('#rail');r.innerHTML='<div class="host-rail-scroll">'+r.innerHTML+'</div><div class="host-rail-footer"><button type="button" data-view="settings" class="host-account"><span class="n">EC</span><span class="lbl">The Architect<small>Estiban Creations · Account</small></span></button><button type="button" data-view="thelma" class="host-thelma"><span class="n">T</span><span class="lbl">THELMA AI<small>Production Assistant</small></span></button><small class="host-release">UI host '+HOSTED_UI_RELEASE+' · canonical Director Studio</small></div>';};
const HOST_ORIGINAL_RENDER=render;
render=function(){HOST_ORIGINAL_RENDER();const v=VW_BOARDS[UI.view]?vwView(UI.view):'V1';document.querySelector('#main').dataset.visualView=v;document.querySelector('#main').dataset.hostRelease=HOSTED_UI_RELEASE;};
const brand=document.querySelector('.topbar .brand');brand.innerHTML='<button type="button" id="hostNavToggle" aria-label="Collapse navigation" aria-expanded="true">☰</button><span>VisionWeaver<small>CREATE · BRING WORLDS TO LIFE</small></span>';
const stats=document.querySelector('.topstats');stats.querySelectorAll('.stat').forEach(el=>el.hidden=true);const tools=stats.querySelector('.tools');tools.innerHTML='<button class="btn primary" type="button" id="hostCreate">Create</button><button class="btn" type="button" id="hostNotifications" aria-label="Notifications">♧</button>';
// Original stat elements remain for canonical renderRail updates; hidden historic credits cannot imply a fresh balance.
const q=document.querySelector('#q');q.placeholder='Search shots, avatars, scenes, assets, and production records…';
const architect=document.querySelector('.architect-menu');if(architect)architect.hidden=true;
const createTargets=[['Avatar Engineering','avatarops'],['Worlds & Locations','worldops'],['Book Creation','source'],['Design Studio','design'],['Commercial Creativity','commercial']];
document.addEventListener('click',e=>{const b=e.target.closest('#hostNavToggle,#hostCreate,#hostNotifications');if(!b)return;if(b.id==='hostNavToggle'){setApp('rail',APP.rail==='icons'?'full':'icons');b.setAttribute('aria-label',APP.rail==='icons'?'Expand navigation':'Collapse navigation');b.setAttribute('aria-expanded',String(APP.rail!=='icons'));}if(b.id==='hostCreate'){const p=document.querySelector('#palette');p.hidden=false;document.querySelector('#pq').value='';document.querySelector('#plist').innerHTML=createTargets.map(([title,page])=>'<button class="btn" data-view="'+page+'">'+title+'</button>').join('');document.querySelector('#pq').focus();}if(b.id==='hostNotifications'){go('guild');}});
if(!location.hash)UI.view='command';
renderRail();render();
